language: node_js
node_js: 
  - "8.10"
cache:
  directories:
  - lambda/custom/node_modules
install:
  - npm install bespoken-tools -g
  - npm install codecov -g
  - cd lambda/custom && npm install && cd ../..
script:
 - bst test
 - codecov


before_deploy:
- cd lambda/custom
deploy:
  - provider: lambda
    function_name: "ask-custom-TC-Safety-Recalls-default"
    region: "us-east-1"
    role: "arn:aws:iam::651996798342:role/ask-lambda-tc-safety-recalls"
    runtime: "nodejs8.10"
    handler_name: "handler"
    local_dir: "lambda"
